# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'WA7_Han_4385' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WA7_Han_4385
  pod 'Alamofire'

end
