# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WA6_Han_4385' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WA6_Han_4385
  pod 'Alamofire'

end
